name: Publish Docs

on:
  push:
    branches: ["main"]
    paths:
      - "docs/**"
  workflow_dispatch:

concurrency:
  group: pages
  cancel-in-progress: true

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  publish:
    name: Build and Deploy Documentation
    uses: ITlusions/ITL.Github/.github/workflows/jekyll-docs.yml@main
    with:
      source: './docs'
      deploy: true
